name: generate_a_kitten
description: A sample dartemis application
dependencies:
  browser: any
  canvas_query:
    path: ../CanvasQuery
  dartemis_toolbox: any
  gamedev_helpers:
    git: https://github.com/denniskaselow/gamedev_helpers
#    path: ../gamedev_helpers
  hop: any
  event_bus: any
